1.  <a href="#intro">Dataset Description</a>
2.  <a href="#asses">Data Assessing</a>
    - <a href="#emp">Employee.csv</a>
    - <a href="#edu">EducationLevel.csv</a>
    - <a href="#perform">_PerformanceRating.csv</a>
    - <a href="#satis">_SatisfiedLevel.csv</a>
    - <a href="#rating">_RatingLevel.csv</a>
3.  <a href="#clean">Data Cleaning</a>
    - <a href="#c_emp">Employee.csv</a>
    - <a href="#c_edu">EducationLevel.csv</a>
    - <a href="#c_perform">_PerformanceRating.csv</a>
    - <a href="#c_satis">_SatisfiedLevel.csv</a>
    - <a href="#c_rating">_RatingLevel.csv</a>

<a id='intro'></a>
### Dataset Description:

### Dataset Introduction
This dataset is designed to provide comprehensive insights into employee performance and satisfaction within the organization. It consists of five interrelated tables, each serving a specific purpose in analyzing various aspects of employee experience and performance metrics.

#### 1. Employee Table ( _Employee.csv_):

This foundational table contains detailed information about each employee, including personal attributes such as name, gender, and salary, as well as professional details like position and educational level. This information is critical for understanding the demographic and professional context of the workforce.

#### 2. Educational Level Table (_EducationLevel.csv_): 
This table categorizes employee educational backgrounds into five distinct levels, ranging from "No Formal Qualifications" to "Doctorate." It serves as a reference for interpreting the education level recorded in the Employee table, facilitating analysis of how educational attainment correlates with performance and satisfaction.

#### 3. Performance Rating Table (_PerformanceRating.csv_): 
This table captures performance evaluations across several dimensions, including Environment Satisfaction, Job Satisfaction, Relationship Satisfaction, Work-Life Balance, Self Rating, and Manager Rating. Each of these metrics is rated on a scale of 1 to 5, enabling a quantitative assessment of employee performance and satisfaction.

#### 4. Satisfied Level Table (_SatisfiedLevel.csv_): 
This table categorizes employee satisfaction into five distinct levels, ranging from "Very Dissatisfied" to "Very Satisfied." It serves as a reference for interpreting the satisfaction ratings recorded in the Performance Rating table.

#### 5. Rating Table (_RatingLevel.csv_): 
Similar to the Satisfied Level Table, this table provides definitions for performance ratings, ranging from "Unacceptable" to "Above and Beyond." This allows for a standardized assessment of employee performance based on managerial evaluations.

#### ***Integration:***
By linking the Performance Rating table with the Satisfied Level and Rating tables, this dataset enables a nuanced analysis of how employee perceptions of their work environment and self-assessments align with managerial evaluations.

##### _Overall, this dataset is a valuable resource for understanding employee dynamics, assessing satisfaction levels, and identifying areas for improvement within the organization. Through careful analysis, it can inform strategies aimed at enhancing employee engagement, productivity, and overall workplace satisfaction._

In [490]:
# Importing Liberaries:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pyodbc
from sqlalchemy import create_engine


<a id='asses'></a>
## Data Assessing:
### _General Properties:_

<a id='emp'></a>
#### ***1. Employee Table:***

In [493]:
# Load the Employee Dataset:
df_emp= pd.read_csv("HR/Employee.csv")
df_emp.head()

EmployeeID   FirstName LastName      Gender  Age BusinessTravel  \
0  3012-1A41    Leonelle    Simco      Female   30    Some Travel   
1  CBCB-9C9D     Leonerd    Aland        Male   38    Some Travel   
2  95D7-1CE9       Ahmed    Sykes        Male   43    Some Travel   
3  47A0-559B  Ermentrude   Berrie  Non-Binary   39    Some Travel   
4  42CC-040A       Stace   Savege      Female   29    Some Travel   

        Department  DistanceFromHome (KM) State                Ethnicity  ...  \
0            Sales                     27    IL                    White  ...   
1            Sales                     23    CA                    White  ...   
2  Human Resources                     29    CA  Asian or Asian American  ...   
3       Technology                     12    IL                    White  ...   
4  Human Resources                     29    CA                    White  ...   

   MaritalStatus  Salary StockOptionLevel OverTime    HireDate  Attrition  \
0       Divorced  102059                1       No  2012-01-03         No   
1         Single  157718                0      Yes  2012-01-04         No   
2        Married  309964                1       No  2012-01-04         No   
3        Married  293132                0       No  2012-01-05         No   
4         Single   49606                0       No  2012-01-05        Yes   

  YearsAtCompany YearsInMostRecentRole YearsSinceLastPromotion  \
0             10                     4                       9   
1             10                     6                      10   
2             10                     6                      10   
3             10                    10                      10   
4              6                     1                       1   

   YearsWithCurrManager  
0                     7  
1                     0  
2                     8  
3                     0  
4                     6  

[5 rows x 23 columns]

In [494]:
df_emp.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 23 columns):
 #   Column                   Non-Null Count  Dtype 
---  ------                   --------------  ----- 
 0   EmployeeID               1470 non-null   object
 1   FirstName                1470 non-null   object
 2   LastName                 1470 non-null   object
 3   Gender                   1470 non-null   object
 4   Age                      1470 non-null   int64 
 5   BusinessTravel           1470 non-null   object
 6   Department               1470 non-null   object
 7   DistanceFromHome (KM)    1470 non-null   int64 
 8   State                    1470 non-null   object
 9   Ethnicity                1470 non-null   object
 10  Education                1470 non-null   int64 
 11  EducationField           1470 non-null   object
 12  JobRole                  1470 non-null   object
 13  MaritalStatus            1470 non-null   object
 14  Salary                   1470 non-null  

In [495]:
print('The table has a shape of:',df_emp.shape)

The table has a shape of: (1470, 23)


In [496]:
if df_emp.isna().sum().sum()== 0:
    print ('No NULL values in this table')
else:
    print('Total number of Null Values is: ',df_emp.isna().sum().sum())

No NULL values in this table


In [497]:
if df_emp.duplicated().sum()== 0:
    print ('No DUPLICATED values in this table')
else:
    print('Total number of Duplicated Values is: ',df_emp.duplicated().sum())

No DUPLICATED values in this table


In [498]:
print('The number of UNIQUE values in this table:\n\n',df_emp.nunique())

The number of UNIQUE values in this table:

 EmployeeID                 1470
FirstName                  1334
LastName                   1441
Gender                        4
Age                          34
BusinessTravel                3
Department                    3
DistanceFromHome (KM)        45
State                         3
Ethnicity                     7
Education                     5
EducationField                9
JobRole                      13
MaritalStatus                 3
Salary                     1455
StockOptionLevel              4
OverTime                      2
HireDate                   1192
Attrition                     2
YearsAtCompany               11
YearsInMostRecentRole        11
YearsSinceLastPromotion      11
YearsWithCurrManager         11
dtype: int64


In [499]:
print('"Gender" Categories:\n',df_emp.Gender.unique())
print('\n"BusinessTravel" Categories:\n',df_emp.BusinessTravel.unique())
print('\n"Department" Categories:\n',df_emp.Department.unique())
print('\n"State" Categories:\n',df_emp.State.unique())
print('\n"Ethnicity" Categories:\n',df_emp.Ethnicity.unique())
print('\n"Education" Categories:\n',df_emp.Education.unique())
print('\n"EducationField" Categories:\n',df_emp.EducationField.unique())
print('\n"JobRole" Categories:\n',df_emp.JobRole.unique())
print('\n"MaritalStatus" Categories:\n',df_emp.MaritalStatus.unique())
print('\n"StockOptionLevel" Categories:\n',df_emp.StockOptionLevel.unique())
print('\n"OverTime" Categories:\n',df_emp.OverTime.unique())
print('\n"Attrition" Categories:\n',df_emp.Attrition.unique())

"Gender" Categories:
 ['Female' 'Male' 'Non-Binary' 'Prefer Not To Say']

"BusinessTravel" Categories:
 ['Some Travel' 'No Travel ' 'Frequent Traveller']

"Department" Categories:
 ['Sales' 'Human Resources' 'Technology']

"State" Categories:
 ['IL' 'CA' 'NY']

"Ethnicity" Categories:
 ['White' 'Asian or Asian American' 'Mixed or multiple ethnic groups'
 'Black or African American' 'Native Hawaiian ' 'Other '
 'American Indian or Alaska Native']

"Education" Categories:
 [5 4 3 2 1]

"EducationField" Categories:
 ['Marketing' 'Marketing ' 'Computer Science' 'Technical Degree'
 'Information Systems' 'Other' 'Economics' 'Human Resources'
 'Business Studies']

"JobRole" Categories:
 ['Sales Executive' 'HR Business Partner' 'Engineering Manager' 'Recruiter'
 'Data Scientist' 'Machine Learning Engineer' 'Manager'
 'Software Engineer' 'Senior Software Engineer' 'Sales Representative'
 'Analytics Manager' 'HR Executive' 'HR Manager']

"MaritalStatus" Categories:
 ['Divorced' 'Single' 'Married

In [500]:
print(f'Employee Ages are ranging from {df_emp.Age.min()} to {df_emp.Age.max()} Years')

Employee Ages are ranging from 18 to 51 Years


In [501]:
print('Home-Work Distance is ranging from {} to {} KM'.format(df_emp['DistanceFromHome (KM)'].min(),df_emp['DistanceFromHome (KM)'].max()))

Home-Work Distance is ranging from 1 to 45 KM


In [502]:
print(f'Salary is in the range of {df_emp.Salary.min()} to {df_emp.Salary.max()} USD/Year')

Salary is in the range of 20387 to 547204 USD/Year


In [503]:
print(f'The recorded Employee Hire dates are starting from {df_emp.HireDate.min()} to {df_emp.HireDate.max()}')

The recorded Employee Hire dates are starting from 2012-01-03 to 2022-12-31


In [504]:
if df_emp.YearsAtCompany.min()== 0:
    print(f'The Working Span of each employee is ranging from less than a year to {df_emp.YearsAtCompany.max()} Years')
else:
    print(f'The Working Span of each employee is ranging from {df_emp.YearsAtCompany.min()} to {df_emp.YearsAtCompany.max()} Years')

The Working Span of each employee is ranging from less than a year to 10 Years


In [505]:
if df_emp.YearsInMostRecentRole.min()== 0:
    print(f'The Time Spent in the current position for each employee is ranging from less than a year to {df_emp.YearsInMostRecentRole.max()} Years')
else:
    print(f'The Time Spent in the current position for each employee is ranging from {df_emp.YearsInMostRecentRole.min()} to {df_emp.YearsInMostRecentRole.max()} Years')

The Time Spent in the current position for each employee is ranging from less than a year to 10 Years


In [506]:
if df_emp.YearsSinceLastPromotion.min()== 0:
    print(f'The Promotion Gap for each employee is ranging from less than a year to {df_emp.YearsSinceLastPromotion.max()} Years')
else:
    print(f'The Promotion Gap for each employee is ranging from {df_emp.YearsSinceLastPromotion.min()} to {df_emp.YearsSinceLastPromotion.max()} Years')

The Promotion Gap for each employee is ranging from less than a year to 10 Years


In [507]:
if df_emp.YearsWithCurrManager.min()== 0:
    print(f'The Working Span of each employee under the current manager is ranging from less than a year to {df_emp.YearsWithCurrManager.max()} Years')
else:
    print(f'The Working Span of each employee under the current manager is ranging from {df_emp.YearsWithCurrManager.min()} to {df_emp.YearsWithCurrManager.max()} Years')

The Working Span of each employee under the current manager is ranging from less than a year to 10 Years


<a id='edu'></a>
#### ***2. Educational Level Table:***

In [509]:
df_edu= pd.read_csv("HR/EducationLevel.csv")
df_edu.head()

EducationLevelID            EducationLevel
0                 1  No Formal Qualifications
1                 2              High School 
2                 3                Bachelors 
3                 4                  Masters 
4                 5                 Doctorate

In [510]:
df_edu.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 2 columns):
 #   Column            Non-Null Count  Dtype 
---  ------            --------------  ----- 
 0   EducationLevelID  5 non-null      int64 
 1   EducationLevel    5 non-null      object
dtypes: int64(1), object(1)
memory usage: 212.0+ bytes


In [511]:
print('The table has a shape of:',df_edu.shape)

The table has a shape of: (5, 2)


In [512]:
if df_edu.isna().sum().sum()== 0:
    print ('No NULL values in this table')
else:
    print('Total number of Null Values is: ',df_edu.isna().sum().sum())


No NULL values in this table


In [513]:
if df_edu.duplicated().sum()== 0:
    print ('No DUPLICATED values in this table')
else:
    print('Total number of Duplicated Values is: ',df.duplicated().sum())

No DUPLICATED values in this table


In [514]:
print('The number of UNIQUE values in this table:\n\n',df_edu.nunique())

The number of UNIQUE values in this table:

 EducationLevelID    5
EducationLevel      5
dtype: int64


In [515]:
print('"EducationLevelID" Categories:\n',df_edu.EducationLevelID.unique())
print('\n"EducationLevel" Categories:\n',df_edu.EducationLevel.unique())

"EducationLevelID" Categories:
 [1 2 3 4 5]

"EducationLevel" Categories:
 ['No Formal Qualifications' 'High School ' 'Bachelors ' 'Masters '
 'Doctorate']


<a id='perform'></a>
#### ***3. Performance Rating Table:***

In [517]:
df_performance= pd.read_csv("HR/PerformanceRating.csv")
df_performance.head()

PerformanceID EmployeeID ReviewDate  EnvironmentSatisfaction  \
0          PR01  79F7-78EC   1/2/2013                        5   
1          PR02  B61E-0F26   1/3/2013                        5   
2          PR03  F5E3-48BB   1/3/2013                        3   
3          PR04  0678-748A   1/4/2013                        5   
4          PR05  541F-3E19   1/4/2013                        5   

   JobSatisfaction  RelationshipSatisfaction  TrainingOpportunitiesWithinYear  \
0                4                         5                                1   
1                4                         4                                1   
2                4                         5                                3   
3                3                         2                                2   
4                2                         3                                1   

   TrainingOpportunitiesTaken  WorkLifeBalance  SelfRating  ManagerRating  
0                           0                4           4              4  
1                           3                4           4              3  
2                           2                3           5              4  
3                           0                2           3              2  
4                           0                4           4              3

In [518]:
df_performance.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6709 entries, 0 to 6708
Data columns (total 11 columns):
 #   Column                           Non-Null Count  Dtype 
---  ------                           --------------  ----- 
 0   PerformanceID                    6709 non-null   object
 1   EmployeeID                       6709 non-null   object
 2   ReviewDate                       6709 non-null   object
 3   EnvironmentSatisfaction          6709 non-null   int64 
 4   JobSatisfaction                  6709 non-null   int64 
 5   RelationshipSatisfaction         6709 non-null   int64 
 6   TrainingOpportunitiesWithinYear  6709 non-null   int64 
 7   TrainingOpportunitiesTaken       6709 non-null   int64 
 8   WorkLifeBalance                  6709 non-null   int64 
 9   SelfRating                       6709 non-null   int64 
 10  ManagerRating                    6709 non-null   int64 
dtypes: int64(8), object(3)
memory usage: 576.7+ KB


In [519]:
print('The table has a shape of:',df_performance.shape)

The table has a shape of: (6709, 11)


In [520]:
if df_performance.isna().sum().sum()== 0:
    print ('No NULL values in this table')
else:
    print('Total number of Null Values is: ',df_performance.isna().sum().sum())


No NULL values in this table


In [521]:
if df_performance.duplicated().sum()== 0:
    print ('No DUPLICATED values in this table')
else:
    print('Total number of Duplicated Values is: ',df_performance.duplicated().sum())


No DUPLICATED values in this table


In [522]:
print('The number of UNIQUE values in this table:\n\n',df_performance.nunique())

The number of UNIQUE values in this table:

 PerformanceID                      6709
EmployeeID                         1280
ReviewDate                         2771
EnvironmentSatisfaction               5
JobSatisfaction                       5
RelationshipSatisfaction              5
TrainingOpportunitiesWithinYear       3
TrainingOpportunitiesTaken            4
WorkLifeBalance                       5
SelfRating                            3
ManagerRating                         4
dtype: int64


In [523]:
df_performance.ReviewDate.min()

'1/1/2014'

In [524]:
df_performance.ReviewDate.max()

'9/9/2019'

In [221]:
df_performance.head()

PerformanceID EmployeeID ReviewDate  EnvironmentSatisfaction  \
0          PR01  79F7-78EC   1/2/2013                        5   
1          PR02  B61E-0F26   1/3/2013                        5   
2          PR03  F5E3-48BB   1/3/2013                        3   
3          PR04  0678-748A   1/4/2013                        5   
4          PR05  541F-3E19   1/4/2013                        5   

   JobSatisfaction  RelationshipSatisfaction  TrainingOpportunitiesWithinYear  \
0                4                         5                                1   
1                4                         4                                1   
2                4                         5                                3   
3                3                         2                                2   
4                2                         3                                1   

   TrainingOpportunitiesTaken  WorkLifeBalance  SelfRating  ManagerRating  
0                           0                4           4              4  
1                           3                4           4              3  
2                           2                3           5              4  
3                           0                2           3              2  
4                           0                4           4              3

In [223]:
df_performance.PerformanceID.nunique()

6709

In [225]:
df_performance.EmployeeID.nunique()

1280

In [227]:
df_performance.ReviewDate.min()

'1/1/2014'

In [229]:
df_performance.ReviewDate.max()

'9/9/2019'

In [231]:
df_performance.EnvironmentSatisfaction.nunique()

5

In [233]:
df_performance.EnvironmentSatisfaction.unique()

array([5, 3, 4, 1, 2], dtype=int64)

In [235]:
df_performance.JobSatisfaction.nunique()

5

In [237]:
df_performance.JobSatisfaction.unique()

array([4, 3, 2, 5, 1], dtype=int64)

In [239]:
df_performance.JobSatisfaction.nunique()

5

In [241]:
df_performance.JobSatisfaction.unique()

array([4, 3, 2, 5, 1], dtype=int64)

In [243]:
df_performance.RelationshipSatisfaction.nunique()

5

In [245]:
df_performance.RelationshipSatisfaction.unique()

array([5, 4, 2, 3, 1], dtype=int64)

In [247]:
df_performance.TrainingOpportunitiesWithinYear.nunique()

3

In [249]:
df_performance.TrainingOpportunitiesWithinYear.unique()

array([1, 3, 2], dtype=int64)

In [251]:
df_performance.TrainingOpportunitiesTaken.nunique()

4

In [253]:
df_performance.TrainingOpportunitiesTaken.unique()

array([0, 3, 2, 1], dtype=int64)

In [255]:
df_performance.WorkLifeBalance.nunique()

5

In [257]:
df_performance.WorkLifeBalance.unique()

array([4, 3, 2, 5, 1], dtype=int64)

In [259]:
df_performance.SelfRating.nunique()

3

In [261]:
df_performance.SelfRating.unique()

array([4, 5, 3], dtype=int64)

In [263]:
df_performance.ManagerRating.nunique()

4

In [265]:
df_performance.ManagerRating.unique()

array([4, 3, 2, 5], dtype=int64)

In [ ]:
df_performance.RelationshipSatisfaction.nunique()

In [ ]:
df_performance.RelationshipSatisfaction.unique()

<a id='satis'></a>
#### ***4. Satisfied Level Table:***

In [207]:
df_satisfy= pd.read_csv("HR/SatisfiedLevel.csv")
df_satisfy.info()
df_satisfy.shape
df_satisfy.head()
df_satisfy.SatisfactionID.unique()
df_satisfy.SatisfactionLevel.unique()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 2 columns):
 #   Column             Non-Null Count  Dtype 
---  ------             --------------  ----- 
 0   SatisfactionID     5 non-null      int64 
 1   SatisfactionLevel  5 non-null      object
dtypes: int64(1), object(1)
memory usage: 212.0+ bytes


<a id='rating'></a>
#### ***5. Rating Level Table:***

In [197]:
df_rating= pd.read_csv("HR/RatingLevel.csv")
df_rating.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 2 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   RatingID     5 non-null      int64 
 1   RatingLevel  5 non-null      object
dtypes: int64(1), object(1)
memory usage: 212.0+ bytes


In [201]:
df_rating.shape

(5, 2)

In [199]:
df_rating.head()
df_rating.RatingID.unique()
df_rating.RatingLevel.unique()

RatingID           RatingLevel
0         1          Unacceptable
1         2     Needs Improvement
2         3     Meets Expectation
3         4  Exceeds Expectation 
4         5      Above and Beyond

<a id='clean'></a>
## Data Cleaning:

<a id='c_emp'></a>
#### ***1. Employee Table:***

<a id='c_edu'></a>
#### ***2. Educational Level Table:***

<a id='c_perform'></a>
#### ***3. Performance Rating Table:***

In [471]:
#df_performance['ReviewDate'] = pd.to_datetime(df_performance['ReviewDate']).dt.date

<a id='c_satis'></a>
#### ***4. Satisfied Level Table:***

<a id='c_rating'></a>
#### ***5. Rating Table:***

In [281]:
# Define the connection parameters
server = 'HEND\SQLEXPRESS'  # SQL Server name or IP
database_name = 'Test'  # Name of the new database

# Establish a connection to the SQL Server using Windows Authentication and enabling autocommit
driver = 'ODBC Driver 17 for SQL Server'
connection_string = f'DRIVER={driver};SERVER={server};Trusted_Connection=yes;'
connection = pyodbc.connect(connection_string, autocommit=True)  # Enable autocommit

# Create a new cursor
cursor = connection.cursor()

# SQL command to create a new database
create_db_query = f"CREATE DATABASE {database_name}"

try:
    # Execute the SQL command
    cursor.execute(create_db_query)
    print(f"Database '{database_name}' created successfully.")
except:
    print("The database is already created")

# Close the cursor and connection
cursor.close()
connection.close()

Database 'Test' created successfully.


In [273]:
connect_db= f'mssql://@{server}/{database_name}?driver={driver}'
engine = create_engine(connect_db)
con_db= engine.connect()

In [275]:
df_performance.to_sql('performance', engine, index=False)

-1

In [277]:
df_satisfy.to_sql('satisfaction', engine, index=False)

-1

In [279]:
df_rating.to_sql('rating', engine, index=False)

-1