In [2]:
# Importing Liberaries:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sqlalchemy import create_engine

In [35]:
# Load the Employee Dataset:
df_emp= pd.read_csv("HR/Employee.csv")
df_emp.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 23 columns):
 #   Column                   Non-Null Count  Dtype 
---  ------                   --------------  ----- 
 0   EmployeeID               1470 non-null   object
 1   FirstName                1470 non-null   object
 2   LastName                 1470 non-null   object
 3   Gender                   1470 non-null   object
 4   Age                      1470 non-null   int64 
 5   BusinessTravel           1470 non-null   object
 6   Department               1470 non-null   object
 7   DistanceFromHome (KM)    1470 non-null   int64 
 8   State                    1470 non-null   object
 9   Ethnicity                1470 non-null   object
 10  Education                1470 non-null   int64 
 11  EducationField           1470 non-null   object
 12  JobRole                  1470 non-null   object
 13  MaritalStatus            1470 non-null   object
 14  Salary                   1470 non-null  

In [37]:
df_emp.head()

EmployeeID   FirstName LastName      Gender  Age BusinessTravel  \
0  3012-1A41    Leonelle    Simco      Female   30    Some Travel   
1  CBCB-9C9D     Leonerd    Aland        Male   38    Some Travel   
2  95D7-1CE9       Ahmed    Sykes        Male   43    Some Travel   
3  47A0-559B  Ermentrude   Berrie  Non-Binary   39    Some Travel   
4  42CC-040A       Stace   Savege      Female   29    Some Travel   

        Department  DistanceFromHome (KM) State                Ethnicity  ...  \
0            Sales                     27    IL                    White  ...   
1            Sales                     23    CA                    White  ...   
2  Human Resources                     29    CA  Asian or Asian American  ...   
3       Technology                     12    IL                    White  ...   
4  Human Resources                     29    CA                    White  ...   

   MaritalStatus  Salary StockOptionLevel OverTime    HireDate  Attrition  \
0       Divorced  102059                1       No  2012-01-03         No   
1         Single  157718                0      Yes  2012-01-04         No   
2        Married  309964                1       No  2012-01-04         No   
3        Married  293132                0       No  2012-01-05         No   
4         Single   49606                0       No  2012-01-05        Yes   

  YearsAtCompany YearsInMostRecentRole YearsSinceLastPromotion  \
0             10                     4                       9   
1             10                     6                      10   
2             10                     6                      10   
3             10                    10                      10   
4              6                     1                       1   

   YearsWithCurrManager  
0                     7  
1                     0  
2                     8  
3                     0  
4                     6  

[5 rows x 23 columns]

In [39]:
df_emp.EmployeeID.nunique()

1470

In [41]:
df_emp.FirstName.nunique()

1334

In [43]:
df_emp.LastName.nunique()

1441

In [45]:
df_emp.Gender.nunique()

4

In [47]:
df_emp.Gender.unique()

array(['Female', 'Male', 'Non-Binary', 'Prefer Not To Say'], dtype=object)

In [57]:
df_emp.Age.unique()

array([30, 38, 43, 39, 29, 34, 42, 40, 31, 32, 35, 37, 33, 45, 36, 48, 47,
       44, 28, 41, 46, 27, 26, 25, 24, 23, 22, 21, 49, 50, 20, 19, 51, 18],
      dtype=int64)

In [59]:
df_emp.Age.min()

18

In [61]:
df_emp.Age.max()

51

In [63]:
df_emp.BusinessTravel.nunique()

3

In [65]:
df_emp.BusinessTravel.unique()

array(['Some Travel', 'No Travel ', 'Frequent Traveller'], dtype=object)

In [67]:
df_emp.Department.nunique()

3

In [69]:
df_emp.Department.unique()

array(['Sales', 'Human Resources', 'Technology'], dtype=object)

In [73]:
df_emp['DistanceFromHome (KM)'].nunique()

45

In [75]:
df_emp['DistanceFromHome (KM)'].min()

1

In [77]:
df_emp['DistanceFromHome (KM)'].max()

45

In [79]:
df_emp.State.nunique()

3

In [81]:
df_emp.State.unique()

array(['IL', 'CA', 'NY'], dtype=object)

In [83]:
df_emp.Ethnicity.nunique()

7

In [85]:
df_emp.Ethnicity.unique()

array(['White', 'Asian or Asian American',
       'Mixed or multiple ethnic groups', 'Black or African American',
       'Native Hawaiian ', 'Other ', 'American Indian or Alaska Native'],
      dtype=object)

In [89]:
df_emp.Education.nunique()

5

In [91]:
df_emp.Education.unique()

array([5, 4, 3, 2, 1], dtype=int64)

In [95]:
df_emp.EducationField.nunique()

9

In [97]:
df_emp.EducationField.unique()

array(['Marketing', 'Marketing ', 'Computer Science', 'Technical Degree',
       'Information Systems', 'Other', 'Economics', 'Human Resources',
       'Business Studies'], dtype=object)

In [99]:
df_emp.JobRole.nunique()

13

In [101]:
df_emp.JobRole.unique()

array(['Sales Executive', 'HR Business Partner', 'Engineering Manager',
       'Recruiter', 'Data Scientist', 'Machine Learning Engineer',
       'Manager', 'Software Engineer', 'Senior Software Engineer',
       'Sales Representative', 'Analytics Manager', 'HR Executive',
       'HR Manager'], dtype=object)

In [103]:
df_emp.MaritalStatus.nunique()

3

In [105]:
df_emp.MaritalStatus.unique()

array(['Divorced', 'Single', 'Married'], dtype=object)

In [107]:
df_emp.Salary.unique()

array([102059, 157718, 309964, ...,  63375,  46521,  38258], dtype=int64)

In [109]:
df_emp.Salary.min()

20387

In [111]:
df_emp.Salary.max()

547204

In [113]:
df_emp.StockOptionLevel.unique()

array([1, 0, 2, 3], dtype=int64)

In [115]:
df_emp.OverTime.unique()

array(['No', 'Yes'], dtype=object)

In [117]:
df_emp.HireDate.min()

'2012-01-03'

In [119]:
df_emp.HireDate.max()

'2022-12-31'

In [121]:
df_emp.Attrition.nunique()

2

In [123]:
df_emp.Attrition.unique()

array(['No', 'Yes'], dtype=object)

In [125]:
df_emp.YearsAtCompany.unique()

array([10,  6,  8,  5,  7,  9,  2,  4,  3,  1,  0], dtype=int64)

In [129]:
df_emp.YearsAtCompany.min()

0

In [131]:
df_emp.YearsAtCompany.max()

10

In [127]:
df_emp.YearsInMostRecentRole.unique()

array([ 4,  6, 10,  1,  3,  2,  5,  7,  8,  9,  0], dtype=int64)

In [133]:
df_emp.YearsInMostRecentRole.min()

0

In [135]:
df_emp.YearsInMostRecentRole.max()

10

In [149]:
df_emp.YearsSinceLastPromotion.min()

0

In [151]:
df_emp.YearsSinceLastPromotion.max()

10

In [145]:
df_emp.YearsWithCurrManager.min()

0

In [147]:
df_emp.YearsWithCurrManager.max()

10